### ISSUE TITLE
请问如何在模版上加入更新时间？

### ISSUE THREAD

**Issue by saddit** [yiyungent/afdian-action#2]
```cshtml
@{
    var curDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
    <span>更新时间：@curDate</span>
}
```

目的是为了每次执行都有不同的结果，防止action报错。但是这段代码无法通过编译，想知道有什么办法插入时间

**Comment by yiyungent** [comment]
> ```
> @{
>     var curDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
>     <span>更新时间：@curDate</span>
> }
> ```
> 
> 目的是为了每次执行都有不同的结果，防止action报错。但是这段代码无法通过编译，想知道有什么办法插入时间

@saddit 报的啥错方便贴出来看看吗？？

可能是缺少 using 命名空间引用了

**Comment by yiyungent** [comment]
```yml
      - name: Afdian action
        uses: yiyungent/afdian-action@main
        with:
          # 在 Settings->Secrets 配置 AFDIAN_USERID, AFDIAN_TOKEN
          # 爱发电 user_id
          afdian_userId: ${{ secrets.AFDIAN_USERID }}
          # 爱发电 token
          afdian_token: ${{ secrets.AFDIAN_TOKEN }}
          # 默认为: .github/afdian-action.cshtml
          template_filePath: ".github/afdian-action.cshtml"
          # 默认为: README.md
          target_filePath: "README.md"
          # 可省, 高级选项: RazorEngine Complie, 在 cshtml 中需要 using 的 namespace, 多个用 ; 隔开
          usings: "System"
          # 可省, 高级选项: RazorEngine Complie, 在 cshtml 中需要添加的 系统引用, 多个用 ; 隔开
          # 例如: assemblyReferences: "System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
          assemblyReferences: "System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
```

- https://github.com/yiyungent/PluginCore/blob/main/.github/workflows/afdian-action.yml
